Adding Leather Works support
KnightMiner/Inspirations pull request #115
Opened 2019-03-26 21:54 UTC by Balint66

Adding plugin for Leather Works mod, and updating forgegradle to be able to use curseforge maven API.

2019-03-27 02:24 UTC, KnightMiner commented
Can you fix formatting to match the rest of the mod? Notably, brackets on the same line and sorted imports.

Also, I think I can guess by looking at the code, but mind giving a brief description of what this plugin does for the sake of documentation?

Side note, unless I'm calling that mods APIs I skip it as a build dependency so I don't need to always boot with it. Currently I just test using the libs folder, but I like the curseforge maven idea. Maybe keep it but leave leatherworks commented out?

2019-03-27 05:20 UTC, Balint66 commented
Of course. I will reformat my code and give a better description.

Oh, yes, sorry I forgot to comment out/delete the leather works dependenci line, my bad. 😅
I used it so I can search in it in my ide so I didn't have to switch between github and the ide.

I will change my code as soon as I can get to my computer.

2019-03-27 20:00 UTC, KnightMiner requested changes
I've left a couple more comments, but have one last question:

Is there any sort of time delay in Leather Works for making leather? I assume its barrel acts basically like my cauldrons, but want to make sure as otherwise it needs to be rebalanced (for example, with potions I only give you two potions instead of 3 to make up for instant crafting)

2019-03-27 20:18 UTC, Balint66 commented on src/main/java/knightminer/inspirations/plugins/leatherworks/LeatherWorksPlugin.java
> +            InspirationsRegistry.addCauldronWater(tannin);
Oh, for some reason I thought that it was for registering fluids. My bad.

2019-03-27 20:26 UTC, Balint66 commented
Leather Works use up the fluid instantly so it does not need any rebalance.

2019-04-16 03:28 UTC, KnightMiner commented
Just wanted to update this to say the changes look good, just have not had a chance to test this yet. Will have time this weekend.

2019-04-18 07:32 UTC, Balint66 commented
I'm glad to hear it. 🙂

2019-04-19 03:33 UTC, KnightMiner approved these changes

2019-04-19 03:34 UTC, merged

2019-04-19 03:35 UTC, KnightMiner commented
Just tested it and it looked great, seems their barrels already act a lot like cauldrons so it fits very well.